// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9H8jCi3XpP2Mgtl-tNr-IdZqcNv9j1M',
    appId: '1:672992345447:web:84bbcb9c937859646403c2',
    messagingSenderId: '672992345447',
    projectId: 'gozip-app',
    authDomain: 'gozip-app.firebaseapp.com',
    storageBucket: 'gozip-app.appspot.com',
    measurementId: 'G-HKB6M2LYX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlFA183pPzPLpNSp6xdwMRP0I-rCwQdNQ',
    appId: '1:672992345447:android:1335764562ae191b6403c2',
    messagingSenderId: '672992345447',
    projectId: 'gozip-app',
    storageBucket: 'gozip-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJqKxykBLdysko3TNtl9JxmU39Geh3J6c',
    appId: '1:672992345447:ios:963b86c0bf8ee53b6403c2',
    messagingSenderId: '672992345447',
    projectId: 'gozip-app',
    storageBucket: 'gozip-app.appspot.com',
    iosBundleId: 'com.example.gozip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJqKxykBLdysko3TNtl9JxmU39Geh3J6c',
    appId: '1:672992345447:ios:08acc00971bb5cd36403c2',
    messagingSenderId: '672992345447',
    projectId: 'gozip-app',
    storageBucket: 'gozip-app.appspot.com',
    iosBundleId: 'com.example.gozip.RunnerTests',
  );
}
